#!/usr/bin/env bash
# ============================================================
# setup-asterisk.sh  —  Simson VPS full audio stack setup
#
# Installs and configures:
#   • Asterisk 20 LTS  (SIP + WebSocket for phones / browser)
#   • coturn           (STUN + TURN — fixes audio with symmetric NAT / HTTPS)
#
# Run as root (sudo) on a fresh Ubuntu/Debian VPS BEFORE starting
# simson-server for the first time.
#
# Usage:
#   sudo bash setup-asterisk.sh [--domain YOUR_VPS_FQDN]
#
# After this script finishes, copy the printed config snippets into:
#   • /opt/simson/config.json        (VPS server config)
#   • Addon → Simson config → webrtc section (per-node HA addon options)
# ============================================================
set -euo pipefail

ASTERISK_VERSION="${ASTERISK_VERSION:-20}"
TURN_PORT="${TURN_PORT:-3478}"
TURN_TLS_PORT="${TURN_TLS_PORT:-5349}"
SIMSON_CONFIG="${SIMSON_CONFIG:-/opt/simson/config.json}"

# ── Parse args ──────────────────────────────────────────────
VPS_DOMAIN=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --domain) VPS_DOMAIN="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

# ── Helpers ──────────────────────────────────────────────────
info()    { printf '\e[32m[+]\e[0m %s\n' "$*"; }
warn()    { printf '\e[33m[!]\e[0m %s\n' "$*"; }
die()     { printf '\e[31m[x]\e[0m %s\n' "$*" >&2; exit 1; }
section() { printf '\n\e[1;34m══ %s ══\e[0m\n' "$*"; }
genpass() { tr -dc 'A-Za-z0-9_-' </dev/urandom | head -c "${1:-32}"; }

[[ $EUID -eq 0 ]] || die "Run this script as root (sudo $0)"

section "Detecting public IP"
PUBLIC_IP=$(curl -fsSL https://ifconfig.me 2>/dev/null || \
            curl -fsSL https://api.ipify.org 2>/dev/null || \
            hostname -I | awk '{print $1}')
info "Public IP: ${PUBLIC_IP}"

if [[ -z "$VPS_DOMAIN" ]]; then
    VPS_DOMAIN="$PUBLIC_IP"
    warn "No --domain given — using IP address: ${VPS_DOMAIN}"
    warn "For production, rerun with: sudo $0 --domain YOUR_FQDN"
fi

section "System packages"
apt-get update -qq

DEBIAN_FRONTEND=noninteractive apt-get install -y \
    asterisk \
    asterisk-modules \
    asterisk-config \
    asterisk-core-sounds-en \
    coturn

# ── Generate credentials ─────────────────────────────────────
section "Generating credentials"

TURN_USER="simson"
TURN_SECRET=$(genpass 40)
WEBRTC_USER="webrtc-pool"
WEBRTC_PASS=$(genpass 32)

info "TURN secret:       ${TURN_SECRET}"
info "SIP WebRTC pass:   ${WEBRTC_PASS}"

# ── coturn configuration ──────────────────────────────────────
section "Configuring coturn"

TURN_CONF=/etc/turnserver.conf

cat > "$TURN_CONF" << EOF
# Simson coturn configuration — auto-generated by setup-asterisk.sh
listening-port=${TURN_PORT}
tls-listening-port=${TURN_TLS_PORT}
listening-ip=${PUBLIC_IP}
relay-ip=${PUBLIC_IP}
external-ip=${PUBLIC_IP}

# Realm (must match TURN URL in client config)
realm=${VPS_DOMAIN}

# Static credential
user=${TURN_USER}:${TURN_SECRET}

# Security
fingerprint
lt-cred-mech
no-loopback-peers
no-multicast-peers

# Logging
log-file=/var/log/coturn/turnserver.log
simple-log

# Uncomment these if you have TLS cert from Certbot/Caddy:
# cert=/etc/letsencrypt/live/${VPS_DOMAIN}/fullchain.pem
# pkey=/etc/letsencrypt/live/${VPS_DOMAIN}/privkey.pem
EOF

# Enable coturn service
sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn 2>/dev/null || \
    echo "TURNSERVER_ENABLED=1" >> /etc/default/coturn

mkdir -p /var/log/coturn
chown -R turnserver:turnserver /var/log/coturn 2>/dev/null || true

systemctl enable coturn
systemctl restart coturn

info "coturn listening on port ${TURN_PORT} (STUN+TURN)"

# ── Firewall rules (ufw) ─────────────────────────────────────
section "Firewall"
if command -v ufw &>/dev/null; then
    ufw allow ${TURN_PORT}/tcp comment "TURN TCP" 2>/dev/null || true
    ufw allow ${TURN_PORT}/udp comment "TURN UDP" 2>/dev/null || true
    ufw allow ${TURN_TLS_PORT}/tcp comment "TURN TLS" 2>/dev/null || true
    ufw allow 5060/udp comment "SIP UDP" 2>/dev/null || true
    ufw allow 10000:20000/udp comment "RTP media" 2>/dev/null || true
    info "ufw rules added"
else
    warn "ufw not found — open these ports manually:"
    warn "  ${TURN_PORT}/tcp+udp, ${TURN_TLS_PORT}/tcp, 5060/udp, 10000-20000/udp"
fi

# ── Asterisk service ─────────────────────────────────────────
section "Asterisk"
systemctl enable asterisk
systemctl start  asterisk || true

# ── Config.d directories ─────────────────────────────────────
info "Creating Asterisk include directories…"
install -d -m 0750 -o asterisk -g asterisk \
    /etc/asterisk/pjsip.conf.d \
    /etc/asterisk/manager.conf.d \
    /etc/asterisk/extensions.conf.d

# Ensure minimal manager.conf if missing
MANAGER_CONF=/etc/asterisk/manager.conf
if ! grep -qE '^\s*enabled\s*=\s*yes' "$MANAGER_CONF" 2>/dev/null; then
    cat > "$MANAGER_CONF" << 'MGEOF'
[general]
enabled = yes
port = 5038
bindaddr = 127.0.0.1
MGEOF
    chown asterisk:asterisk "$MANAGER_CONF"
fi

# ── Update Caddyfile for /sip/ws ─────────────────────────────
section "Caddy"
CADDYFILE=$(find /etc/caddy /opt/simson -name "Caddyfile" 2>/dev/null | head -1 || true)
if [[ -n "$CADDYFILE" ]]; then
    if ! grep -q '/sip/ws' "$CADDYFILE"; then
        # Inject /sip/ws block before the closing brace of the first server block
        sed -i '/handle \/ws {/i\\t\thandle /sip/ws {\n\t\t\treverse_proxy localhost:8088\n\t\t}\n' "$CADDYFILE" 2>/dev/null || \
        warn "Could not auto-update Caddyfile — add the /sip/ws block manually (see below)"
    else
        info "Caddyfile already has /sip/ws — skipping"
    fi
    systemctl reload caddy 2>/dev/null || true
else
    warn "Caddyfile not found — add the /sip/ws proxy block manually"
fi

# ── Summary ──────────────────────────────────────────────────
ASTERISK_FULL=$(asterisk -V 2>/dev/null || echo "unknown")
COTURN_VER=$(turnserver -v 2>&1 | head -1 || echo "unknown")

section "Setup complete — copy the snippets below into your configs"

printf '\n\e[1;33m══ /opt/simson/config.json  →  paste inside the root object ══\e[0m\n'
cat << CFGEOF
  "asterisk": {
    "enabled": true,
    "host": "127.0.0.1",
    "port": 5038,
    "user": "simson",
    "secret": "CHANGE_ME_IN_CONFIG",
    "auto_configure": true,
    "sip_domain": "${VPS_DOMAIN}",
    "external_ip": "${PUBLIC_IP}",
    "in_context": "from-simson-sip",
    "node_context": "from-simson-node",
    "sip_webrtc": {
      "enabled": true,
      "username": "${WEBRTC_USER}",
      "password": "${WEBRTC_PASS}",
      "ws_path": "/sip/ws"
    }
  },
  "ice": {
    "stun_servers": [
      "stun:stun.l.google.com:19302",
      "stun:${VPS_DOMAIN}:${TURN_PORT}"
    ],
    "turn_enabled": true,
    "turn_urls": ["turn:${VPS_DOMAIN}:${TURN_PORT}"],
    "turn_username": "${TURN_USER}",
    "turn_secret": "${TURN_SECRET}"
  }
CFGEOF

printf '\n\e[1;33m══ HA Addon Config  →  paste into Simson addon options ══\e[0m\n'
cat << ADDONEOF
webrtc:
  turn_enabled: true
  turn_url: "turn:${VPS_DOMAIN}:${TURN_PORT}"
  turn_username: "${TURN_USER}"
  turn_credential: "${TURN_SECRET}"
  sip_enabled: true
  sip_ws_url: "wss://${VPS_DOMAIN}/sip/ws"
  sip_username: "${WEBRTC_USER}"
  sip_password: "${WEBRTC_PASS}"
  sip_domain: "${VPS_DOMAIN}"
ADDONEOF

printf '\n'
info "────────────────────────────────────────────────"
info "Asterisk: ${ASTERISK_FULL}"
info "coturn:   ${COTURN_VER}"
info ""
info "Next steps:"
info "  1. Copy the config.json snippet above into /opt/simson/config.json"
info "  2. Copy the addon snippet into Simson → Configuration → webrtc"
info "  3. Run:  sudo systemctl restart simson"
info "  4. Verify:  curl -s http://localhost:${TURN_PORT} (should get STUN error — that's OK)"
info ""
info "TLS TURN (optional, for HTTPS pages that block plain TURN):"
info "  Uncomment the cert/pkey lines in /etc/turnserver.conf once"
info "  Let's Encrypt certs are available, then: systemctl restart coturn"
info "────────────────────────────────────────────────"

