package asterisk

import (
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/nitish-mp3/simson-vps/logging"
)

// ---- public types -----------------------------------------------------------

// SetupConfig holds parameters for auto-configuring Asterisk on the VPS.
type SetupConfig struct {
	AmiUser     string
	AmiSecret   string
	SIPDomain   string // PJSIP transport domain / hostname seen by phones
	ExternalIP  string // Public IP for RTP NAT traversal (empty → omit external_media_address)
	InContext   string // dialplan context for incoming SIP calls ("from-simson-sip")
	NodeContext string // dialplan context for node-callback channels ("from-simson-node")
	// Shared SIP-over-WebSocket endpoint for browser SIP.js clients.
	// Empty Username disables the webrtc-pool endpoint.
	WebRTCUser string
	WebRTCPass string
}

// SIPEndpointDef is a minimal view of a SIP endpoint used when writing pjsip.conf.
// It mirrors store.SIPEndpoint but avoids an import cycle.
type SIPEndpointDef struct {
	ID       string
	Username string
	Password string
	Enabled  bool
}

// Setup writes all Asterisk config files needed by the Simson VPS and reloads
// the relevant Asterisk modules. It is idempotent — safe to call on every start.
func Setup(cfg SetupConfig, endpoints []SIPEndpointDef, log *logging.Logger) error {
	root := findAsteriskRoot()
	if root == "" {
		return fmt.Errorf(
			"asterisk config root not found (tried /etc/asterisk, /usr/local/etc/asterisk). " +
				"Install Asterisk first: sudo apt install asterisk",
		)
	}

	if err := writeManagerConf(root, cfg.AmiUser, cfg.AmiSecret); err != nil {
		return fmt.Errorf("manager.conf: %w", err)
	}
	if err := writePJSIPConf(root, cfg, endpoints); err != nil {
		return fmt.Errorf("pjsip.conf: %w", err)
	}
	if err := writeConfBridgeConf(root); err != nil {
		return fmt.Errorf("confbridge.conf: %w", err)
	}
	if err := writeDialplanConf(root, cfg.InContext, cfg.NodeContext); err != nil {
		return fmt.Errorf("extensions.conf: %w", err)
	}

	log.Info("asterisk config written", map[string]any{"root": root})

	if err := reloadModules(log); err != nil {
		return fmt.Errorf("reload: %w", err)
	}
	return nil
}

// ---- internal ---------------------------------------------------------------

var asteriskRoots = []string{
	"/etc/asterisk",
	"/usr/local/etc/asterisk",
}

func findAsteriskRoot() string {
	for _, p := range asteriskRoots {
		if info, err := os.Stat(p); err == nil && info.IsDir() {
			return p
		}
	}
	return ""
}

// ensureInclude appends a #include directive to confFile if not already present.
func ensureInclude(confFile, glob string) error {
	data, _ := os.ReadFile(confFile) // file may not exist — ignore err
	content := string(data)
	normGlob := strings.ReplaceAll(glob, "\\", "/")
	dirPattern := filepath.Base(filepath.Dir(normGlob)) + "/*.conf"
	line := "#include " + glob
	if strings.Contains(content, line) || strings.Contains(content, normGlob) || strings.Contains(content, dirPattern) {
		return nil
	}
	f, err := os.OpenFile(confFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = fmt.Fprintf(f, "\n; Added by Simson VPS server\n%s\n", line)
	return err
}

// detectSnippetDirName picks the snippet dir already included by a base conf.
// Falls back to fallbackDir when no include is present.
func detectSnippetDirName(root, confFile string, candidates []string, fallbackDir string) string {
	data, _ := os.ReadFile(filepath.Join(root, confFile))
	content := strings.ReplaceAll(string(data), "\"", "")
	for _, name := range candidates {
		pattern := name + "/*.conf"
		if strings.Contains(content, pattern) || strings.Contains(content, "/"+pattern) {
			return name
		}
	}
	return fallbackDir
}

// ---- manager.conf -----------------------------------------------------------

func writeManagerConf(root, amiUser, amiSecret string) error {
	dirName := detectSnippetDirName(root, "manager.conf", []string{"manager.d", "manager.conf.d"}, "manager.d")
	dir := filepath.Join(root, dirName)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	if err := ensureInclude(
		filepath.Join(root, "manager.conf"),
		dirName+"/*.conf",
	); err != nil {
		return err
	}

	content := fmt.Sprintf(
		`; Auto-generated by Simson VPS server — do not edit manually.
; Re-generated on every server start when asterisk.auto_configure = true.
[general]
enabled = yes
port = 5038
bindaddr = 127.0.0.1

[%s]
secret = %s
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.255
read = all
write = all
writetimeout = 5000
`, amiUser, amiSecret)

	dest := filepath.Join(dir, "simson.conf")
	return os.WriteFile(dest, []byte(content), 0640)
}

// ---- pjsip.conf -------------------------------------------------------------

func writePJSIPConf(root string, cfg SetupConfig, endpoints []SIPEndpointDef) error {
	dirName := detectSnippetDirName(root, "pjsip.conf", []string{"pjsip.d", "pjsip.conf.d"}, "pjsip.d")
	dir := filepath.Join(root, dirName)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	if err := ensureInclude(
		filepath.Join(root, "pjsip.conf"),
		dirName+"/*.conf",
	); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("; Auto-generated by Simson VPS server — do not edit manually.\n\n")
	externalIP := strings.TrimSpace(cfg.ExternalIP)
	if externalIP == "" {
		externalIP = resolveExternalIPFromDomain(cfg.SIPDomain)
	}

	// ── UDP transport ──────────────────────────────────────────────────────────
	// Used by IP phones (desk phones, softphones) for SIP signalling.
	sb.WriteString("[simson-udp]\ntype=transport\nprotocol=udp\nbind=0.0.0.0:5060\n")
	if cfg.SIPDomain != "" {
		sb.WriteString("domain=" + cfg.SIPDomain + "\n")
	}
	// External IP lets Asterisk advertise the correct public address in SDP,
	// preventing the "audio not passing" problem caused by RFC1918 in SDP/RTP.
	appendTransportNATConfig(&sb, externalIP)
	sb.WriteString("\n")

	// ── Plain WebSocket transport (browser SIP.js / Simson card) ─────────────
	// TLS is handled upstream by Caddy which proxies /sip/ws → localhost:8088.
	// We intentionally omit a native WSS transport — the self-signed cert
	// Asterisk would need isn't available and browsers would reject it anyway.
	sb.WriteString("[simson-ws]\ntype=transport\nprotocol=ws\nbind=0.0.0.0:8088\n")
	if cfg.SIPDomain != "" {
		sb.WriteString("domain=" + cfg.SIPDomain + "\n")
	}
	appendTransportNATConfig(&sb, externalIP)
	sb.WriteString("\n")

	// ── Global settings (STUN for Asterisk's own ICE negotiation) ────────────
	sb.WriteString("[global]\ntype=global\nmax_initial_qualify_time=60\n\n")

	// ── Endpoint template (shared settings for all Simson phones) ─────────────
	sb.WriteString(
		"[simson-ep-tpl](!)\ntype=endpoint\n" +
			"context=from-simson-sip\n" +
			"disallow=all\n" +
			"allow=ulaw\nallow=alaw\nallow=g722\nallow=opus\n" +
			"direct_media=no\n" +
			"rtp_symmetric=yes\n" +
			"force_rport=yes\n" +
			"rewrite_contact=yes\n" +
			"ice_support=yes\n" +
			"media_encryption=no\n" +
			"dtmf_mode=rfc4733\n\n",
	)
	sb.WriteString("[simson-auth-tpl](!)\ntype=auth\nauth_type=userpass\n\n")
	sb.WriteString("[simson-aor-tpl](!)\ntype=aor\nmax_contacts=2\nremove_existing=yes\nqualify_frequency=60\n\n")
	sb.WriteString(
		"[simson-webrtc-ep-tpl](!)\ntype=endpoint\n" +
			"transport=simson-ws\n" +
			"context=from-simson-node\n" +
			"disallow=all\n" +
			"allow=opus\nallow=ulaw\nallow=alaw\n" +
			"direct_media=no\n" +
			"rtp_symmetric=yes\n" +
			"force_rport=yes\n" +
			"rewrite_contact=yes\n" +
			"ice_support=yes\n" +
			"webrtc=yes\n" +
			"use_avpf=yes\n" +
			"rtcp_mux=yes\n" +
			"media_use_received_transport=yes\n" +
			"media_encryption=dtls\n" +
			"dtls_auto_generate_cert=yes\n" +
			"dtls_setup=actpass\n" +
			"dtmf_mode=rfc4733\n\n",
	)

	// ── Shared WebRTC pool endpoint (for browser SIP.js clients) ─────────────
	// All browser clients use the same credentials; individual routing is done
	// via the ConfBridge extension, not the SIP identity.
	if cfg.WebRTCUser != "" && cfg.WebRTCPass != "" {
		sb.WriteString(
			"[simson-webrtc-pool](simson-webrtc-ep-tpl)\n" +
				"auth=simson-webrtc-pool-auth\n" +
				"aors=simson-webrtc-pool-aor\n\n",
		)
		fmt.Fprintf(&sb, "[simson-webrtc-pool-auth](simson-auth-tpl)\nusername=%s\npassword=%s\n\n",
			cfg.WebRTCUser, cfg.WebRTCPass)
		sb.WriteString("[simson-webrtc-pool-aor](simson-aor-tpl)\nmax_contacts=50\n\n")
	}

	// ── Per-endpoint entries (registered SIP phones / devices) ────────────────
	for _, ep := range endpoints {
		if !ep.Enabled {
			continue
		}
		id := sanitizeID(ep.ID)
		fmt.Fprintf(&sb, "[%s](simson-ep-tpl)\nauth=%s-auth\naors=%s-aor\n\n", id, id, id)
		fmt.Fprintf(&sb, "[%s-auth](simson-auth-tpl)\nusername=%s\npassword=%s\n\n", id, ep.Username, ep.Password)
		fmt.Fprintf(&sb, "[%s-aor](simson-aor-tpl)\n\n", id)
	}

	return os.WriteFile(filepath.Join(dir, "simson.conf"), []byte(sb.String()), 0640)
}

// ---- extensions.conf --------------------------------------------------------

func writeConfBridgeConf(root string) error {
	dirName := detectSnippetDirName(root, "confbridge.conf", []string{"confbridge.conf.d", "confbridge.d"}, "confbridge.conf.d")
	dir := filepath.Join(root, dirName)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	if err := ensureInclude(
		filepath.Join(root, "confbridge.conf"),
		dirName+"/*.conf",
	); err != nil {
		return err
	}

	content := `; Auto-generated by Simson VPS server — do not edit manually.
[simson_bridge]
type=bridge
max_members=10
record_conference=no
video_mode=none
`

	return os.WriteFile(filepath.Join(dir, "simson.conf"), []byte(content), 0640)
}

// ---- extensions.conf --------------------------------------------------------

func writeDialplanConf(root, inCtx, nodeCtx string) error {
	dirName := detectSnippetDirName(root, "extensions.conf", []string{"extensions.d", "extensions.conf.d"}, "extensions.d")
	dir := filepath.Join(root, dirName)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	if err := ensureInclude(
		filepath.Join(root, "extensions.conf"),
		dirName+"/*.conf",
	); err != nil {
		return err
	}

	// Safety fallbacks
	if inCtx == "" {
		inCtx = "from-simson-sip"
	}
	if nodeCtx == "" {
		nodeCtx = "from-simson-node"
	}

	content := fmt.Sprintf(
		`; Auto-generated by Simson VPS server — do not edit manually.
;
; Architecture:
;   [%s]  — IP phones call numbers here → Asterisk fires UserEvent:SimsonRoute
;              → Go VPS server routes to the correct Simson WebSocket node
;              → audio is held in a ConfBridge room until the node's SIP UA joins
;   [%s] — Simson nodes join the ConfBridge room (extension = bridge ID)
;              e.g. PJSIP/node-my-pi dials bridge-<uniqueid> here
;
[%s]
; Catch-all: route every incoming SIP call to the Simson control plane.
exten => _X.,1,NoOp(Simson: incoming call to ${EXTEN} from ${CALLERID(num)})
 same  => n,Set(SIMSON_BRIDGE_ID=bridge-${UNIQUEID})
 same  => n,UserEvent(SimsonRoute,Extension: ${EXTEN},Caller: ${CALLERID(num)},UniqueID: ${UNIQUEID},Bridge: ${SIMSON_BRIDGE_ID},Channel: ${CHANNEL})
 same  => n,ConfBridge(${SIMSON_BRIDGE_ID},simson_bridge)
 same  => n,Hangup()

; Voicemail / no answer fallback.
exten => i,1,Hangup(21)
exten => t,1,Hangup(16)

[%s]
; Simson node SIP UA dials the bridge ID as the extension to join the audio path.
exten => _bridge-.,1,NoOp(Simson node joining bridge ${EXTEN})
 same  => n,Answer()
 same  => n,ConfBridge(${EXTEN},simson_bridge)
 same  => n,Hangup()

; extension "s" — for Originate from VPS (answer + wait to be bridged)
exten => s,1,NoOp(Simson originate leg)
 same  => n,Answer()
 same  => n,Wait(${SIMSON_WAIT_TIMEOUT:=120})
 same  => n,Hangup()
`, inCtx, nodeCtx, inCtx, nodeCtx)

	return os.WriteFile(filepath.Join(dir, "simson.conf"), []byte(content), 0640)
}

// ---- module reload ----------------------------------------------------------

func reloadModules(log *logging.Logger) error {
	cmds := []string{
		"manager reload",
		"pjsip reload",
		"dialplan reload",
		"module reload app_confbridge.so",
	}
	for _, cmd := range cmds {
		out, err := exec.Command("asterisk", "-rx", cmd).CombinedOutput()
		if err != nil {
			return fmt.Errorf("asterisk -rx %q: %w (output: %s)", cmd, err, string(out))
		}
		log.Debug("asterisk reload", map[string]any{"cmd": cmd, "output": strings.TrimSpace(string(out))})
	}
	return nil
}

func appendTransportNATConfig(sb *strings.Builder, externalIP string) {
	ip := strings.TrimSpace(externalIP)
	if ip == "" {
		return
	}
	sb.WriteString("external_media_address=" + ip + "\n")
	sb.WriteString("external_signaling_address=" + ip + "\n")
	sb.WriteString("local_net=127.0.0.0/8\nlocal_net=10.0.0.0/8\nlocal_net=172.16.0.0/12\nlocal_net=192.168.0.0/16\n")
}

func resolveExternalIPFromDomain(domain string) string {
	host := strings.TrimSpace(domain)
	if host == "" {
		return ""
	}
	if h, _, err := net.SplitHostPort(host); err == nil {
		host = h
	}
	host = strings.Trim(host, "[]")
	if ip := net.ParseIP(host); ip != nil {
		if v4 := ip.To4(); v4 != nil {
			return v4.String()
		}
		return ""
	}
	ips, err := net.LookupIP(host)
	if err != nil {
		return ""
	}
	for _, ip := range ips {
		if v4 := ip.To4(); v4 != nil && !v4.IsPrivate() {
			return v4.String()
		}
	}
	for _, ip := range ips {
		if v4 := ip.To4(); v4 != nil {
			return v4.String()
		}
	}
	return ""
}

// sanitizeID strips unsafe characters from an endpoint ID.
func sanitizeID(id string) string {
	var sb strings.Builder
	for _, r := range id {
		if r == '-' || r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			sb.WriteRune(r)
		}
	}
	return sb.String()
}
