[INCLUDES]
before = common.conf

[Definition]
failregex = ^\s*(?:\[[^\]]*\]\s*)?NOTICE\[\d+\]:?\s+res_pjsip_session\.c:(?:\d+\s+(?:in\s+)?new_invite:)?\s+Call from 'anonymous' \((?:UDP|TCP):<HOST>:\d+\) to extension '[^']*' rejected because extension not found in context 'from-simson-anonymous'\.$
            ^\s*(?:\[[^\]]*\]\s*)?NOTICE\[\d+\]:?\s+res_pjsip/pjsip_distributor\.c:(?:\d+\s+(?:in\s+)?log_failed_request:)?\s+Request (?:'[^']*' )?from '[^']*' failed for '<HOST>:\d+' \(callid: [^\)]*\) - (?:No matching endpoint found|Failed to authenticate)\s*$
            ^\s*(?:\[[^\]]*\]\s*)?SECURITY\[\d+\]:?\s+res_security_log\.c:\s+SecurityEvent="FailedACL",EventTV="[^"]*",Severity="[^"]*",Service="PJSIP",EventVersion="\d+",AccountID="anonymous",SessionID="[^"]*",LocalAddress="[^"]*",RemoteAddress="IPV[46]/(?:UDP|TCP|TLS|WS|WSS)/<HOST>/\d+",ACLName="registrar_attempt_without_configured_aors"\s*$
ignoreregex =
